### ISSUE TITLE
[chess] Pieces Are Not Square

### ISSUE THREAD

**Issue by JamesonRGrieve-Instruction** [JamesonRGrieve-Instruction/EXSM-3936-LEC-WI2-Demo#3]
### Description

The chess pieces are not square (do not have a 1:1 aspect ratio).

### Steps to Reproduce the Bug

Start the application `start ./src/index.html`.

### Expected Behavior

The chess pieces are square, contained in a circle (not an oval). 

### Actual Behavior

The chess pieces are contained in ovals (most of them).

### Additional Context / Screenshots

![image](https://github.com/JamesonRGrieve-Instruction/EXSM-3936-LEC-WI2-Demo/assets/66742895/4cd4f7ed-8a61-4951-9f5a-c2a763e08214)

**Comment by jmantei** [comment]
Worked on this.
